Repository BlueBrain/Search, pull requests merged in 2021-08, with the labels that each got.

#407 Back up MySQL database
  docker/mysql-make-backup
  docker/mysql.Dockerfile
Labels: 🗄️ database

#391 #355 Integrate Sentence Embedding training and fine-tuning in DVC pipeline.
  .mypy.ini
  data_and_models/models/language_modeling/.gitignore
  data_and_models/pipelines/sentence_embedding/.gitignore
  data_and_models/pipelines/sentence_embedding/Dockerfile
  data_and_models/pipelines/sentence_embedding/dvc.yaml
  data_and_models/pipelines/sentence_embedding/scripts/README.md
  data_and_models/pipelines/sentence_embedding/scripts/build.sh
  data_and_models/pipelines/sentence_embedding/training_transformers/.gitignore
  data_and_models/pipelines/sentence_embedding/training_transformers/biosses_sentences.txt.dvc
  data_and_models/pipelines/sentence_embedding/training_transformers/fine_tune.py
  data_and_models/pipelines/sentence_embedding/training_transformers/sentences-filtered_11-527-877.txt.dvc
  data_and_models/pipelines/sentence_embedding/training_transformers/train.py
  docs/source/whatsnew.rst
  pyproject.toml
  requirements.txt
  setup.py
  tox.ini
Labels: 🦉 dvc

#403 Convert warnings to errors in unit tests
  requirements-data_and_models.txt
  requirements-dev.txt
  requirements.txt
  src/bluesearch/database/mining_cache.py
  src/bluesearch/mining/attribute.py
  src/bluesearch/mining/entity.py
  src/bluesearch/mining/eval.py
  src/bluesearch/widgets/search_widget.py
  tests/conftest.py
  tests/test_database/test_cord_19.py
  tests/test_embedding_models.py
  tests/test_mining/test_eval.py
  tests/test_mining/test_pipeline.py
  tox.ini
Labels: dependencies, 🧪 testing

#417 Make entrypoint startup faster
  docker/embedding.Dockerfile
  docker/mining.sh
  docker/search.Dockerfile
  setup.py
  src/bluesearch/entrypoint/__init__.py
  src/bluesearch/entrypoint/database.py
  src/bluesearch/entrypoint/embeddings.py
  src/bluesearch/entrypoint/mining_cache.py
  tests/test_entrypoint/test_compute_embeddings.py
  tests/test_entrypoint/test_create_database.py
  tests/test_entrypoint/test_create_mining_cache.py
  tests/test_entrypoint/test_embedding_server.py
  tests/test_entrypoint/test_mining_server.py
  tests/test_entrypoint/test_search_sever.py
Labels: 🐛 bug fix, optimization

#415 Rename tests/test_module/ folders to tests/module/
  tests/database/test_article.py
  tests/database/test_cord_19.py
  tests/database/test_mining_cache.py
  tests/entrypoint/__init__.py
  tests/entrypoint/test__helper.py
  tests/entrypoint/test_compute_embeddings.py
  tests/entrypoint/test_create_database.py
  tests/entrypoint/test_create_mining_cache.py
  tests/entrypoint/test_embedding_server.py
  tests/entrypoint/test_entrypoint_installation.py
  tests/entrypoint/test_mining_server.py
  tests/entrypoint/test_search_sever.py
  tests/mining/test_attribute.py
  tests/mining/test_entity.py
  tests/mining/test_eval.py
  tests/mining/test_pipeline.py
  tests/mining/test_relation.py
  tests/server/__init__.py
  tests/server/test_embedding_server.py
  tests/server/test_mining_server.py
  tests/server/test_search_server.py
  tests/widgets/test_article_saver.py
  tests/widgets/test_mining_schema.py
  tests/widgets/test_mining_widget.py
  tests/widgets/test_search_widget.py
Labels: optimization, 🧪 testing
