Repository BlueBrain/Search, pull requests merged in 2021-03, with the labels that each got.

#267 [BBS-266] Adapt Getting Started for DVC remote from Zenodo
  README.md
  docker/mining.sh
  docs/source/whatsnew.rst
Labels: documentation, new feature, 🦉 dvc

#302 Fix the has_table call
  src/bluesearch/database/mining_cache.py
Labels: bug fix

#311 Upgrade to dvc>=2 + release bluesearch v0.1.1
  data_and_models/pipelines/ner/Dockerfile
  data_and_models/pipelines/ner/dvc.lock
  data_and_models/pipelines/sentence_embedding/Dockerfile
  data_and_models/pipelines/sentence_embedding/dvc.lock
  docs/source/whatsnew.rst
  requirements.txt
  setup.py
Labels: 🦉 dvc
