Repository BlueBrain/Search, pull requests merged in 2021-07, with the labels that each got.

#390 Add missing sklearn.metrics import in eval module
  src/bluesearch/mining/eval.py
Labels: 🐛 bug fix

#389 Remove unused SciSpacy models and obsolete mentions thereof
  data_and_models/pipelines/ner/add_er.py
  data_and_models/pipelines/ner/eval.py
  data_and_models/pipelines/ner/transformers_vs_spacy/spacy/eval.py
  notebooks/NER_Evaluation.ipynb
  notebooks/demo_attribute_extraction.ipynb
  requirements-data_and_models.txt
  requirements-dev.txt
  requirements.txt
  setup.py
  src/bluesearch/mining/pipeline.py
Labels: dependencies

#392 Improve docker base image
  docker-compose.yml
  docker/base.Dockerfile
  docker/embedding.Dockerfile
  docker/mining.Dockerfile
  docker/mining_cache.Dockerfile
  docker/search.Dockerfile
  docker/utils.sh
Labels: optimization

#395 Re-run DVC pipelines to release v0.2.0
  data_and_models/metrics/ner/disease.json
  data_and_models/metrics/ner/interrater/disease.json
  data_and_models/metrics/sentence_embedding/biobert_nli_sts.json
  data_and_models/metrics/sentence_embedding/biobert_nli_sts_cord19_v1.json
  data_and_models/metrics/sentence_embedding/sbert.json
  data_and_models/metrics/sentence_embedding/sbiobert.json
  data_and_models/pipelines/ner/Dockerfile
  data_and_models/pipelines/ner/dvc.lock
  data_and_models/pipelines/ner/dvc.yaml
  data_and_models/pipelines/sentence_embedding/Dockerfile
  data_and_models/pipelines/sentence_embedding/dvc.lock
  docs/source/whatsnew.rst
Labels: 🦉 dvc

#393 #375 Test linting of "data_and_models/"
  .mypy.ini
  data_and_models/annotations/ner/analyze.py
  data_and_models/pipelines/ner/add_er.py
  data_and_models/pipelines/ner/clean.py
  data_and_models/pipelines/ner/dvc.yaml
  data_and_models/pipelines/ner/eval_ner.py
  data_and_models/pipelines/ner/interrater.py
  data_and_models/pipelines/ner/preprocess.py
  data_and_models/pipelines/ner/transformers_vs_spacy/spacy/compare_tokens.py
  data_and_models/pipelines/ner/transformers_vs_spacy/spacy/eval.sh
  data_and_models/pipelines/ner/transformers_vs_spacy/spacy/eval_spacy.py
  data_and_models/pipelines/relation_extraction/convert_chemprot_fmt.py
  data_and_models/pipelines/sentence_embedding/dvc.yaml
  data_and_models/pipelines/sentence_embedding/eval_se.py
  data_and_models/pipelines/sentence_embedding/train.py
  pyproject.toml
  src/bluesearch/mining/eval.py
  tox.ini
Labels: linting / formatting / cleaning

#404 Fix the definition of DVC pipeline sentence_embedding
  data_and_models/pipelines/sentence_embedding/dvc.lock
  data_and_models/pipelines/sentence_embedding/dvc.yaml
  docs/source/whatsnew.rst
Labels: 🐛 bug fix, 🦉 dvc
